### ISSUE TITLE
How install this?

### ISSUE THREAD

**Issue by letarg0** [begriffs/c-mix#2]
1. What I must install before creating exe file program? (dnf install ghc)
1. How big are the program. For example how big is python, Ruby version or Perl6. (realy small, my exe are 10kb ; $strip ./hello)
1. How integrating C fnction as Hascell function? (this is possible? meybe not function only interface)
1.  how serring my own type in haskell, for example defining x = x*x but not on integer only long or long long

**Comment by begriffs** [comment]
All you need is GHC, a C compiler, and make. Clone the repo and run `make` to build the binary.

The resulting binary is 20K, but requires a shared haskell library to run on another machine. You could choose to statically link the executable instead, but it will be a lot bigger.

I added another function to show how to pass the `long long` type between C and Haskell.

**Comment by letarg0** [comment]
result is no static. How compiling static?

I have trouble with 2 parameter i must long->long->long?
Why?
