### ISSUE TITLE
Is it possible to generate Makefile by CMake?

### ISSUE THREAD

**Issue by vincent-hui** [begriffs/c-mix#3]
Is it possible to generate Makefile by CMake? If yes, would you mind writing a cmakelists.txt ?
Thank you.

**Comment by begriffs** [comment]
What's your motivation?

**Comment by vincent-hui** [comment]
To make integrating it into projects using cmake build systems easier.

**Comment by begriffs** [comment]
Sorry, I don't care about cmake. :)
